// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/archive/[tag].tsx";
import * as $2 from "./routes/archive/index.tsx";
import * as $3 from "./routes/author/[author].tsx";
import * as $4 from "./routes/blog/[slug].tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/archive/[tag].tsx": $1,
    "./routes/archive/index.tsx": $2,
    "./routes/author/[author].tsx": $3,
    "./routes/blog/[slug].tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
