name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Check types
        run: deno check **/*.ts && deno check **/*.tsx

      - name: Cache Chrome (Linux)
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno/deno_puppeteer
          key: chrome-1022525-${{ runner.os }}-${{ hashFiles('tests/deps.ts') }}
          restore-keys: chrome-1022525-${{ runner.os }}-

      - name: Install Chromium (Unix)
        run: PUPPETEER_PRODUCT=chrome deno run -A https://deno.land/x/puppeteer@16.2.0/install.ts

      - name: Run tests
        run: deno test -A --no-check --coverage=cov/
        env:
          BLOG_NOTION_API_KEY: ${{ secrets.BLOG_NOTION_API_KEY }}
          BLOG_NOTION_DATABASE_ID: ${{ secrets.BLOG_NOTION_DATABASE_ID }}

      - name: Generate coverage
        run: deno coverage --lcov cov/ > cov.lcov

      - name: Upload coverage to Coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: cov.lcov
